### ISSUE TITLE
Does Spring ClusterMonitorFactory register clusterMonitor at run time????

### ISSUE THREAD

**Issue by JagmohanSharma** [spring-cloud/spring-cloud-release#64] opened 2016-10-04 12:23 UTC
We have overridden the ClusterMonitorFactory for getting cluster names which then register the clusterMonitor. As- 

                 private List<String> getClusterNames() {

                             List<String> clusters = new ArrayList<String>();
                            List<ServiceInstance> serviceInstances = discoveryClient.getAllInstances();
                             for (ServiceInstance serviceInstance : serviceInstances) {
                                            try {
                                               clusters.add(serviceInstance.getServiceId());
                                           } catch (Exception ex) {

                                            }
                                 }
                         return clusters;
                      }

here we are getting cluster name from consul registered services.

Now as this is used in AggregatorFactory to initialise the clusterMonitors same as default implementation -

                                 @Override
    public void initClusterMonitors() {
        for (String clusterName : getClusterNames()) {
            ClusterMonitor<AggDataFromCluster> clusterMonitor = (ClusterMonitor<AggDataFromCluster>) findOrRegisterAggregateMonitor(clusterName);
            clusterMonitor.registerListenertoClusterMonitor(StaticListener);
            try {
                clusterMonitor.startMonitor();
            } catch (Exception ex) {
                logger.warn("Could not init cluster monitor for: " + clusterName);
                clusterMonitor.stopMonitor();
                clusterMonitor.getDispatcher().stopDispatcher();
            }
        }
    }

As per our requirement we can have new services getting registered at consul , so this should able to initialise the clusterMonitor for those newly registered services as well without any need to redeploy this application as this initClusterMonitors() is called at the deployment time only.

i found that getInstanceList() method is called on a 1 min duration as defined in InstanceObservable class 

                                                  private final TimerTask producer = new TimerTask() {

        @Override
        public void run() {
            if(observers == null || observers.size() == 0) {
                logger.info("No observers for InstanceObservable, will try again later");
                return; 
            }

            // get the refreshed cluster
            List<Instance> newList = null;
            try {
                newList = **getInstanceList();**

                logger.info("Retrieved hosts from InstanceDiscovery: " + newList.size());
                if(newList.size() < 10) {
                    logger.debug("Retrieved hosts from InstanceDiscovery: " + newList);
                }

which gets all services from consul as per our implementation , so this will fetch all newly registered services from consul at run time without redeployment. But as this cluster name is matched in ObservationCriteria -

                          @Override
        public boolean observeHost(Instance host) {
            if (clusterName == null) {
                return false;
            }
            return clusterName.equals(host.getCluster());
        }

but this clusterName is being set at the start in AggreagtorFactory method implemented from ClusterMonitorFactory - 

                                 public static TurbineDataMonitor<AggDataFromCluster> findOrRegisterAggregateMonitor(
            String clusterName) {
        TurbineDataMonitor<AggDataFromCluster> clusterMonitor = AggregatorClusterMonitorConsole
                .findMonitor(clusterName + "_agg");
        if (clusterMonitor == null) {
            **### clusterMonitor = new SpringClusterMonitor(clusterName + "_agg", clusterName);**
            clusterMonitor = AggregatorClusterMonitorConsole
                    .findOrRegisterMonitor(clusterMonitor);
        }
        return clusterMonitor;
    }

So as per my finding this is not able to set clusterMonitor at run time without any need to redploy the application.. Please correct me if I am wrong and is this possible to make this working without redeployment of application as this is on high priority for me to complete this????????

**Comment by spencergibb** [comment] 2016-10-05 02:00
Duplicate of https://github.com/spring-cloud/spring-cloud-netflix/issues/1350. No need to open multiple tickets. Currently, you are the only one asking for this, so it's not a real high priority for us. Pull requests are welcome.

**Closed by spencergibb** 2016-10-05 02:00 UTC
